#!/bin/bash

usage()
{
    cat << EOF
 usage: $0 [options] "Channel name"

This script will start playing a tvheadend webstream in mplayer

OPTIONS:
    -u      URL to server (http://localhost:9981)
    -a      Audio codec [aac, mpeg2audio, pass, none]
    -v      Video codec [h264, mpeg4video, vp8, pass, none],
    -s      Subtitle codec [pass, none]
    -r      Resolution (height) to use with -v [120 to 576]
    -m      Muxing container [matroska, mpeg2ts, mpegps, pass]
EOF
}


SERVER="http://localhost:9981"
ACODEC=
VCODEC=
SCODEC=
TRANSCODE=
RES=384
MUX=matroska

OPTIND=1
while getopts "ha:v:s:r:m:c:u:" opt; do
    case $opt in
        h)
            usage
            exit 1
            ;;
        a)
            ACODEC="`echo $OPTARG | tr '[:lower:]' '[:upper:]'`"
	    TRANSCODE="1"
            ;;
        v)
            VCODEC="`echo $OPTARG | tr '[:lower:]' '[:upper:]'`"
	    TRANSCODE="1"
            ;;
        s)
            SCODEC="`echo $OPTARG | tr '[:lower:]' '[:upper:]'`"
            TRANSCODE="1"
            ;;
        r)
            RES=$OPTARG
            ;;
        m)
            MUX=$OPTARG
            ;;
        u)
            SERVER=$OPTARG
            ;;
        ?)
            usage
            exit
            ;;
    esac
done
shift $(($OPTIND - 1))

if [ -z "$1" ]; then
    usage
    exit
fi

URL="$SERVER/stream/channel/$1?mux=$MUX"


if [ -n "$TRANSCODE" ]; then
    URL="$URL&transcode=1&resolution=$RES"
fi

if [ -n "$ACODEC" ]; then
    URL="$URL&acodec=$ACODEC"
fi

if [ -n "$VCODEC" ]; then
    URL="$URL&vcodec=$VCODEC"
fi

if [ -n "$SCODEC" ]; then
    URL="$URL&scodec=$SCODEC"
fi

mplayer -cache 4000 -cache-min 50 "$URL"
